import json

unicode_to_name = {}

with open("icons.json", "r",encoding="utf-8") as f:
    icons = json.load(f)

for k,v in icons.items():
    unicode_to_name[v['unicode']] = k

with open("../epass.eez-project","r",encoding="utf-8") as f:
    project = json.load(f)


for font in project['fonts']:
    if font['name'] == 'fontawesome':
        fasymbols = font["lvglRanges"]

codes = []
for part in fasymbols.split(","):
    if "-" in part:
        start,end = part.split("-")
        for code in range(int(start,16), int(end,16)+1):
            codes.append(hex(code)[2:])
    else:
        codes.append(part.replace("0x",""))

print(codes)

with open("icons.h","w",encoding="utf-8") as f:
    f.write("#pragma once\n")
    f.write("// AUTOMATICALLY GENERATED by genheader.py\n")
    f.write("// DO NOT EDIT!\n\n")

    for code in codes:
        if code in unicode_to_name:
            name = unicode_to_name[code].upper().replace("-","_")
            if len(code) == 2:
                f.write(f"#define UI_ICON_{name} \"\\x{code}\"\n")
            else:
                f.write(f"#define UI_ICON_{name} \"\\u{code}\"\n")
        else:
            print(f"Warning: No name found for unicode {code}")
